# Generated by Django 3.2.5 on 2021-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
