# Generated by Django 3.2.5 on 2021-07-27 17:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_file_path),
        ),
    ]
