# Generated by Django 3.2.5 on 2021-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_type'),
        ('account', '0005_alter_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to='post.Post'),
        ),
    ]
