# Generated by Django 3.2.5 on 2021-07-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default='image', max_length=10, null=True),
        ),
    ]
